    shop=document.querySelector(".shop");
    orderList=JSON.parse(localStorage.getItem('orderList'));
    for(i=0;i<orderList.length;i++){
        block=document.createElement("div");
        img=document.createElement('img');
        img.src=`./img/${orderList[i]}`;
        block.classList.add("block");
        img.classList.add("wow");
        img.classList.add("tada");
        block.id=`item${i+1}`;
        block.appendChild(img);
        block.setAttribute('onclick','setRed(this)')
        shop.appendChild(block);
    }
function setRed(block){
    block.classList.toggle("setRed");
}
function buy(){
    if(localStorage.getItem('selectedItem')!=null){
        localStorage.removeItem('selectedItem');
    }
    selectedItem=[];
    blockList=document.querySelectorAll(".block");
    for(i=0;i<blockList.length;i++){
        if(blockList[i].classList.contains("setRed")){
            selectedItem.push(blockList[i].id);
        }
    }
    if(selectedItem.length>0){
        localStorage.setItem('selectedItem',JSON.stringify(selectedItem));
        window.location.href="buy.html";
    }
    else alert("Select item");
}
if(localStorage.getItem('selectedItem')!=null){
    selectedItem=JSON.parse(localStorage.getItem('selectedItem'))
    block=document.querySelectorAll('.block');
    for(i=0;i<block.length;i++){
        for(j=0;j<selectedItem.length;j++){
            if(block[i].id==selectedItem[j])
                block[i].classList.add("setRed");
        }
    }
    console.log(selectedItem)
}